// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCBnpLQ-5N6ugiMiDbd3Jf27E3aSkfTE',
    appId: '1:414494086115:web:8809d13ad595f9becdc6d6',
    messagingSenderId: '414494086115',
    projectId: 'mokafapp',
    authDomain: 'mokafapp.firebaseapp.com',
    databaseURL: 'https://mokafapp-default-rtdb.firebaseio.com',
    storageBucket: 'mokafapp.firebasestorage.app',
    measurementId: 'G-8J0KHKPD56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRNMASYW1cW69-EW-xKGlWFhhaZ2E065k',
    appId: '1:414494086115:android:66be0f3e1ebcb7e0cdc6d6',
    messagingSenderId: '414494086115',
    projectId: 'mokafapp',
    databaseURL: 'https://mokafapp-default-rtdb.firebaseio.com',
    storageBucket: 'mokafapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtbO4-uZLW396UXaup4LwsJAOpDtLmZdk',
    appId: '1:414494086115:ios:433861b4a1f0a7a5cdc6d6',
    messagingSenderId: '414494086115',
    projectId: 'mokafapp',
    databaseURL: 'https://mokafapp-default-rtdb.firebaseio.com',
    storageBucket: 'mokafapp.firebasestorage.app',
    iosBundleId: 'com.example.mokaf2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtbO4-uZLW396UXaup4LwsJAOpDtLmZdk',
    appId: '1:414494086115:ios:433861b4a1f0a7a5cdc6d6',
    messagingSenderId: '414494086115',
    projectId: 'mokafapp',
    databaseURL: 'https://mokafapp-default-rtdb.firebaseio.com',
    storageBucket: 'mokafapp.firebasestorage.app',
    iosBundleId: 'com.example.mokaf2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgCBnpLQ-5N6ugiMiDbd3Jf27E3aSkfTE',
    appId: '1:414494086115:web:42036907d46aa75acdc6d6',
    messagingSenderId: '414494086115',
    projectId: 'mokafapp',
    authDomain: 'mokafapp.firebaseapp.com',
    databaseURL: 'https://mokafapp-default-rtdb.firebaseio.com',
    storageBucket: 'mokafapp.firebasestorage.app',
    measurementId: 'G-LVKPLCDWMG',
  );
}